name: Run tests

on:
  push:
    branches: [dev, main]
  pull_request:
    brances: [dev, main]

jobs:
  api-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install -g pm2
    - run: pm2 start index.js
    - run: npm install -g newman
    - run: newman run test-rest-api/test.postman_collection.json